// DIFF_OP(name, n_operands, value, priority, text, tex_fmt)

DIFF_OP(ADD,    2, (arg1 + arg2),  1, "+",      "%l+%r")
DIFF_OP(SUB,    2, (arg1 - arg2),  1, "-",      "%l-%r")
DIFF_OP(MUL,    2, (arg1 * arg2),  2, "*",      "%l*%r")
DIFF_OP(DIV,    2, (arg1 / arg2),  0, "/",      "\\frac{%l}{%r}")
DIFF_OP(POW,    2, pow(arg1, arg2),  3, "^",      "%l^{%r}")
DIFF_OP(EXP,    1, exp(arg1),  0, "exp",    "exp(%l)")
DIFF_OP(LN,     1, log(arg1),  0, "ln",     "ln(%l)")
DIFF_OP(SIN,    1, sin(arg1),  0, "sin",    "sin(%l)")
DIFF_OP(COS,    1, cos(arg1),  0, "cos",    "cos(%l)") 
DIFF_OP(TAN,    1, tan(arg1),  0, "tan",    "tan(%l)")
DIFF_OP(ARCSIN, 1, asin(arg1), 0, "arcsin", "arcsin(%l)")
DIFF_OP(ARCCOS, 1, acos(arg1), 0, "arccos", "arccos(%l)")
DIFF_OP(ARCTAN, 1, atan(arg1), 0, "arctan", "arctan(%l)") 